import = ["~/.config/alacritty/catppuccin/catppuccin-macchiato.toml"]

live_config_reload = true
[env]
TERM = "xterm-256color"
[window]
decorations = "Buttonless"
dynamic_padding = true
# opacity = 0.97

# [window]
# dynamic_padding=true
# x = 25
# y = 20

[font]
size = 14.0

[font.bold]
# family = "JetBrainsMono Nerd Font"
family = "MesloLGL Nerd Font"
style = "Bold"

[font.bold_italic]
family = "MesloLGL Nerd Font"
# family = "JetBrainsMono Nerd Font"
style = "Bold Italic"

[font.italic]
family = "MesloLGL Nerd Font"
# family = "JetBrainsMono Nerd Font"
style = "Italic"

[font.normal]
family = "MesloLGL Nerd Font"
style = "Regular"
[keyboard]
bindings = [{ key="f", mods="Option", mode="AppCursor",action="ToggleMaximized" },]


